# build docs from docstrings and markdown-file in folder docs
# publish them as github pages

name: docs
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install .
      - run: make docs
      - run: mkdocs gh-deploy --force